version: '3'

services:

  my-flask:
    container_name: flask-app
    build:
      context: .
    networks:
      - two-tier-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: self_db
    depends_on:
      - mysql
    ports:
      - 5000:5000
    restart: unless-stopped

  mysql:
    container_name: mysql-db
    image: mysql
    networks:
      - two-tier-app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: self_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

networks:
  two-tier-app:

volumes:
  mysql_db:
