apiVersion: v1

kind: Service

metadata:
  name: flask-svc
  namespace: my-flask-app

spec:
  selector:
    app_name: flask
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
