apiVersion: v1

kind: PersistentVolume

metadata:
  name: mysql-pv
  namespace: my-flask-app

spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/my-flask-two-tier-app/mysqldata2
