apiVersion: v1

kind: ConfigMap

metadata:
  name: mysql-query-config
  namespace: my-flask-app

data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS self_db;
    USE self_db;
    CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);
